### ISSUE TITLE
Fails on Raspberry Pi OS Debian 10 Buster?

### ISSUE THREAD

**Issue by dachshund-digital** [nicmcd/vcgencmd#5]
Fails on Raspberry Pi OS Debian 10 Buster?

Installed via pip3 install vcgencmd...

    # pip3 install vcgencmd

    Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple

    Requirement already satisfied: vcgencmd in /usr/local/lib/python3.7/dist-packages (0.1.1)

    # python3

    Python 3.7.3 (default, Jan 22 2021, 20:04:44)

    [GCC 8.3.0] on linux

    Type "help", "copyright", "credits" or "license" for more information.

    >>> import vcgencmd

    >>> vcgencmd.measure_temp()

    Traceback (most recent call last):

      File "<stdin>", line 1, in <module>

    AttributeError: module 'vcgencmd' has no attribute 'measure_temp'

    >>>

**Comment by dachshund-digital** [comment]
Version 0.1.0 seems to work, but 0.1.1 does not?  So the direct download and compile of 0.1.0 worked.  But pull of 0.1.1 from the pip3 repository fails.  Guess 0.1.1 is not released correctly?

**Comment by nicmcd** [comment]
The pypi registered "vcgencmd" package is not mine :)
The one you are installing is this one: https://github.com/sushantnadkar/vcgencmd.git

Before you unstall a pypi package, checkout it's pypi info:
https://pypi.org/project/vcgencmd/

**Comment by dachshund-digital** [comment]
Yup, I did not realize there was a conflict.  Thanks for the response, always nice when people support their code!  Pulling the git code works of cousrse.
